// Generated by BUCKLESCRIPT VERSION 2.2.3, PLEASE EDIT WITH CARE
'use strict';


var Basic = 0;

var PromiseMonad = 0;

exports.Basic = Basic;
exports.PromiseMonad = PromiseMonad;
/* No side effect */
